site_name: Documentación de Tagost

theme: 
  name: material
  highlightjs: true
  theme:
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


nav:
  - Inicio: 'index.md'
  - 'Guia de Usuario':
    - 'OpenSSL': 'openssl.md'
    - 'Helm Repository': 'helmcharts-github-pages.md'
    - 'Azure': 'azure.md'
    - 'Nginx': 'nginx.md'
    - 'Docker': 'docker.md'
  - Acerca de: 'about.md'
  