site_name: Documentación de Tagost

theme: 
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  theme:
    palette: 
      scheme: default
      primary: black
      accent: blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Inicio: 'index.md'
  - 'Guia de Usuario':
    - 'OpenSSL': 'openssl.md'
    - 'Helm Repository': 'helmcharts-github-pages.md'
    - 'Azure': 'azure.md'
    - 'Nginx': 'nginx.md'
    - 'Docker': 'docker.md'
  - Acerca de: 'about.md'

extra:
  analytics:
    provider: google
    property: G-40ENHFYR3B

repo_url: https://github.com/tagost/mkdocs
repo_name: squidfunk/mkdocs-material

